services:
  ### Application
  App\User\Application\QueryProcessor:
    arguments:
      - '@App\User\Domain\UserReadStorage'

  ### Domain
  App\User\Domain\UserReadStorage:
    alias: App\User\Infrastructure\Persistence\UserRepository

  ### Infrastructure
  App\User\Infrastructure\Persistence\UserRepository:
    autowire: true
    tags:
      - { name: doctrine.repository_service }
  ### Presentation