services:
  ### Application
  App\User\Application\QueryProcessor:
    arguments:
      - '@App\User\Domain\UserReadStorage'

  App\User\Application\CommandProcessor:
    arguments:
      - '@App\User\Domain\UserWriteStorage'
      - '@App\User\Domain\UserReadStorage'
      - '@security.password_hasher'
      - '@App\User\Application\MessageBuilder'

  App\User\Application\MessageBuilder:
    arguments:
      - '@Symfony\Component\Mailer\MailerInterface'

  ### Domain
  App\User\Domain\UserReadStorage:
    alias: App\User\Infrastructure\Persistence\UserRepository

  App\User\Domain\UserWriteStorage:
    alias: App\User\Infrastructure\Persistence\UserRepository

  ### Infrastructure
  App\User\Infrastructure\Persistence\UserRepository:
    autowire: true
    tags:
      - { name: doctrine.repository_service }
  ### Presentation