services:
  ### Infrastructure
  App\User\Infrastructure\Persistence\UserRepository:
    autowire: true
    tags:
      - { name: doctrine.repository_service }
  ### Presentation
  App\User\Application\QueryProcessor:
    autowire: true

  App\User\DTO\UserDto:
    autowire: true