version: '3.7'

services:
  web:
    networks:
      - gs
    env_file:
      - .env
    volumes:
      - .:/opt/app:delegated
    tmpfs:
      - /tmp
      - /tmp/php-opcache
    depends_on:
      - db
    build:
      context: .
      dockerfile: build/local/Dockerfile
    environment:
      - APP_NAME=web
    expose:
      - 9000

  db:
    image: postgres:12.2
    networks:
      - gs
    volumes:
      - ./var/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    container_name: gs_db
    ports:
      - 5432:5432

  webserver:
    networks:
      - gs
    image: nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - './build/local/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './var/uploads:/usr/share/nginx/uploads'
    restart: always

networks:
  gs:
    driver: "bridge"
    driver_opts:
      com.docker.network.driver.mtu: 1400
