version: '3.3'

services:
  web:
    networks:
      - gs
    env_file:
      - .env
    volumes:
      - .:/opt/app:delegated
    tmpfs:
      - /tmp
      - /tmp/php-opcache
    depends_on:
      - db
    build:
      context: .
      dockerfile: build/local/Dockerfile
    environment:
      - APP_NAME=web
    expose:
      - 9000

  db:
    image: postgres:12.2
    networks:
      - gs
    volumes:
      - ./var/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    container_name: gs_db
    ports:
      - 5432:5432

  webserver:
    networks:
      - gs
    image: nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - './build/local/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './var/uploads:/usr/share/nginx/uploads'
    restart: always

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8081:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json
  redis:
    image: "redis:alpine"
    command: redis-server
    networks:
      - gs
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master
networks:
  gs:
    driver: "bridge"
    driver_opts:
      com.docker.network.driver.mtu: 1400