parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $emailFromAddress: '%env(resolve:EMAIL_FROM_ADDRESS)%'
            $emailFromName: '%env(resolve:EMAIL_FROM_NAME)%'

    user_services:
        namespace: App\User\
        resource: '../src/User/{Application,Domain,Presentation}'
    user_repositories:
        namespace: App\User\Infrastructure\Persistence\
        resource: '../src/User/Infrastructure/Persistence'
        tags: [ doctrine.repository_service ]