### organization type list
GET {{host}}/api/v1/dict/organization/types
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}


### local list
GET {{host}}/api/v1/dict/local
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}
