### check

POST http://gs.local/api/login_check
Content-Type: application/json

{
  "username": "test@test.com",
  "password": "Test1234"
}

> {% client.global.set("auth_token", response.body.token); %}

###