### check

POST {{host}}/api/v1/public/login_check
Content-Type: application/json

{
  "username": "newuser@test.com",
  "password": "Test1234"
}

> {% client.global.set("auth_token", response.body.token); %}

###
