### generate-upload-link

POST {{host}}/api/v1/media/generate-upload-link
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "fileName": "test.pdf"
}
