### organization | add

POST {{host}}/api/v1/organization/
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "name": "Test Organization",
    "description": "desc"
}

> {%client.global.set("organization_uuid", response.body.id); %}

### organization | get

GET {{host}}/api/v1/organization/1ed92842-df9f-650a-afc8-6347d2b33e41
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### organization | list

GET {{host}}/api/v1/organization/
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Origin: https://localhost:3000

### organization | list for select

GET {{host}}/api/v1/organization/select/
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### organization | join

PUT {{host}}/api/v1/organization/{{organization_uuid}}/join/
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}
