### organization | add

POST {{host}}/api/v1/organization/
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "name": "Название",
    "address": "г. Москва, Красная площадь 1",
    "type": "ООО",
    "website": "http://test.org",
    "description": "Описание",
    "vk": "@oloolo",
    "facebook": "@ololoev",
    "instagram": "@vinnie",
    "telegram": "@thepooh"
}

> {%client.global.set("organization_uuid", response.body.id); %}

### organization | get

GET {{host}}/api/v1/organization/{{organization_uuid}}
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### organization | list

GET {{host}}/api/v1/organization/
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}
Origin: https://localhost:3000

### organization | list for select

GET {{host}}/api/v1/organization/select/
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### organization | join

PUT {{host}}/api/v1/organization/{{organization_uuid}}/join/
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}
