### request

POST {{host}}/api/v1/public/user/reset-password/request
Accept: application/json, text/plain, */*
Content-Type: application/json

{
    "email": "admin@test.com"
}

### reset

POST {{host}}/api/v1/public/user/reset-password/
Accept: application/json, text/plain, */*
Content-Type: application/json

{
    "token": "qb1qOudgkrQKa1VdBg0xsZwMXRUI93igzYBpOxpN",
    "plainPassword": "Test1234"
}
