### set-locale

## ru | en | es
PUT {{host}}/api/v1/translation/set-locale
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "locale": "en"
}

### profile | get

GET {{host}}/api/v1/user/profile/
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### profile | update

PUT {{host}}/api/v1/user/profile/
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "firstName": "testname",
    "lastName": "testlastname",
    "birthDate": "2022-12-25",
    "gender": "male",
    "country": "Россия",
    "city": "Владивосток",
    "locale": "ru",
    "phone": "+79990008877",
    "imageUuid": "18bee1c3-7469-42fe-b7ae-1c88645d6232",
    "aboutMe": "Я узнал, что у меня, есть огромная семья. И тропинка, и лесок, в поле каждый колосок, речка, небо голубое",
    "vk": "vk.com/goodserfer",
    "facebook": "fb.com/goodserfer",
    "instagram": "@goodserfer",
    "telegram": "@goodserfer"
}


### user | find by email

POST {{host}}/api/v1/user/find
Accept: application/json, text/plain, */*
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "email": "admin@test.com"
}
