name: CI

on:
    pull_request:

jobs:
    build:
        name: check code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Create infrastructure
              run: |-
                touch .env.local
                docker network create proxy --driver=bridge
            - name: Pull images
              run: docker compose pull
            - name: Build services
              run: docker compose build --pull --no-cache
            - name: Start services
              run: docker compose up -d
            - name: Wait for services
              run: |
                  while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker compose ps -q php)")"; do
                    case $status in
                      starting) sleep 1;;
                      healthy) exit 0;;
                      unhealthy) exit 1;;
                    esac
                  done
                  exit 1
            - name: Check HTTP reachability
              run: curl http://localhost
            - name: Check HTTPS reachability
              run: curl -k https://localhost
